### ISSUE TITLE
Projects not created

### ISSUE THREAD

**Issue by TimLamoureux** [dylanjkotze/zephyr-project-manager#23]
Hi,

I have the latest version of Zephyr (3.0.1) + Pro and WP 5.2. When I create a project from the backend (admin panel), the wheel spins, the form shows up but the project is never saved. If I reopen the project tab, it is not available. 

I tried from the front end and experience the same issue.

More details:
Tasks added on the new project are created and trigger an email alert. They are saved properly but missing for the project.

Adding Kanban columns works as long **as the project page is not reloaded**. If I reload the page, the project disappears.

Any clue what is going on?

PS: Great work! Your plugin is fantastic and I am glad to see so many 5 stars ratings. Wish I had some time to contribute to help you.

**Comment by TimLamoureux** [comment]
Do you prefer to report bugs here or on Wordpress forums? I haven't heard back from you about this issue in 20 days when you are usually quite fast on WP Forums. 

Thanks

**Comment by dylanjkotze** [comment]
Hi Tim,

My sincere apologies for the delay and inconvenience as I only saw this message and issue now.

It seems like there might be a JavaScript error or PHP error that is causing the projects and tasks not to save correctly. Would you perhaps be open to creating a temporary account for me on your website so that I can just take a closer look as to where the error is coming from and fix this as soon as possible?
I think it would perhaps be better to report the bugs or issues on WP Forums or you can contact me directly at dylanjkotze@gmail.com and I will help you ASAP.

I am looking forward to your response and helping you get this resolved as soon as possible.

Thank you for your time.

**Comment by TimLamoureux** [comment]
Hi Dylan,

Thanks for the followup. No hard feelings, the quality of your support is fantastic and it's easy to miss things once in a while :)

I've created an account on our website. Please check your emails for the credentials from yukonskipatrol. I have made you a Zephyr - Administrator.

Thanks for the help

**Comment by dylanjkotze** [comment]
Hi Tim,

Thanks and once again I sincerely apologize for missing it once again and would like to help you get this resolved as soon as possible.

I believe I have found the cause of this issue. Could I kindly ask if you could perhaps send me an email to dylanjkotze@gmail.com or let me know what your email is so that I can send you the updated version to fix this.

Kind regards,
Dylan

**Comment by dylanjkotze** [comment]
Hi Tim,

Hope you are well.

I would just like to follow up on this and see if you received my previous message :)

Thanks for your time.

**Comment by TimLamoureux** [comment]
Hi, I sent you an email where you can contact me :) Sorry for the wait, things got crazy around here.

**Comment by dylanjkotze** [comment]
Hi,

Thank you and no worry about the delay, I know how crazy things can get :)

I have sent the email with the updated versions, please let me know how it goes.

Thanks.
